galaxy_info:
  author: Nick Celebic
  description: configure remi
  company: Quicken Loans
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 0.1
  platforms:
    - name: EL
      versions:
        - 5
        - 6
        - 7
  galaxy_tags: []
dependencies: []
